// Code generated by Kitex v0.9.1. DO NOT EDIT.

package example

import (
	"context"
	example "github.com/arfaghifari/ki-call/kitex_gen/example"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ExampleFunc(ctx context.Context, Req *example.ExampleRequest, callOptions ...callopt.Option) (r *example.ExampleResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kExampleClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kExampleClient struct {
	*kClient
}

func (p *kExampleClient) ExampleFunc(ctx context.Context, Req *example.ExampleRequest, callOptions ...callopt.Option) (r *example.ExampleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExampleFunc(ctx, Req)
}
