// Code generated by Kitex v0.9.1. DO NOT EDIT.

package example

import (
	"context"
	"errors"
	example "github.com/arfaghifari/ki-call/kitex_gen/example"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ExampleFunc": kitex.NewMethodInfo(
		exampleFuncHandler,
		newExampleFuncArgs,
		newExampleFuncResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	exampleServiceInfo                = NewServiceInfo()
	exampleServiceInfoForClient       = NewServiceInfoForClient()
	exampleServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return exampleServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return exampleServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return exampleServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Example"
	handlerType := (*example.Example)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "example",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func exampleFuncHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(example.ExampleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(example.Example).ExampleFunc(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ExampleFuncArgs:
		success, err := handler.(example.Example).ExampleFunc(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ExampleFuncResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newExampleFuncArgs() interface{} {
	return &ExampleFuncArgs{}
}

func newExampleFuncResult() interface{} {
	return &ExampleFuncResult{}
}

type ExampleFuncArgs struct {
	Req *example.ExampleRequest
}

func (p *ExampleFuncArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(example.ExampleRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ExampleFuncArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ExampleFuncArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ExampleFuncArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ExampleFuncArgs) Unmarshal(in []byte) error {
	msg := new(example.ExampleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ExampleFuncArgs_Req_DEFAULT *example.ExampleRequest

func (p *ExampleFuncArgs) GetReq() *example.ExampleRequest {
	if !p.IsSetReq() {
		return ExampleFuncArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ExampleFuncArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ExampleFuncArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ExampleFuncResult struct {
	Success *example.ExampleResponse
}

var ExampleFuncResult_Success_DEFAULT *example.ExampleResponse

func (p *ExampleFuncResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(example.ExampleResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ExampleFuncResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ExampleFuncResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ExampleFuncResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ExampleFuncResult) Unmarshal(in []byte) error {
	msg := new(example.ExampleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ExampleFuncResult) GetSuccess() *example.ExampleResponse {
	if !p.IsSetSuccess() {
		return ExampleFuncResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ExampleFuncResult) SetSuccess(x interface{}) {
	p.Success = x.(*example.ExampleResponse)
}

func (p *ExampleFuncResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ExampleFuncResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ExampleFunc(ctx context.Context, Req *example.ExampleRequest) (r *example.ExampleResponse, err error) {
	var _args ExampleFuncArgs
	_args.Req = Req
	var _result ExampleFuncResult
	if err = p.c.Call(ctx, "ExampleFunc", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
